name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: "https://r0k77nztt7.execute-api.us-east-1.amazonaws.com/dev/users"
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Create env file
        run: | # cp sample.env.yml env.yml
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy Lambda functions
        run: sls deploy --stage dev
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambda-users
          source: index.js
